lock-version = "1.0"
created-by = "pip"

[[packages]]
name = "pyyaml"
version = "6.0.3"

[[packages.wheels]]
name = "pyyaml-6.0.3-cp314-cp314-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/23/20/bb6982b26a40bb43951265ba29d4c246ef0ff59c9fdcdf0ed04e0687de4d/pyyaml-6.0.3-cp314-cp314-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "4a2e8cebe2ff6ab7d1050ecd59c25d4c8bd7e6f400f5f82b96557ac0abafd0ac"
